### ISSUE TITLE
utf8检测失败

### ISSUE THREAD

**Issue by hiwanz** [wayfind/is-utf8#2]
用sublimetext3保存为utf8文件，检测失败

var fs = require('fs');
var isUtf8 = require('is-utf8');

var utf8 = fs.readFileSync('test.html');

console.log('test.html is utf8: '+isUtf8(utf8));

**Comment by wayfind** [comment]
是不是文件字节不够大。至少要有两个汉字。

**Comment by hiwanz** [comment]
抱歉，问题太久了，整理gist的时候被我删掉了，最近又遇到了一次打包demo上来

> node test.js
> utf8.js is utf8: false

[utf8-test.zip](https://github.com/wayfind/is-utf8/files/72148/utf8-test.zip)
