### ISSUE TITLE
What BSD License it belongs to?

### ISSUE THREAD

**Issue by Kandy16** [wayfind/is-utf8#3]
Hey,
 Thanks for the good effort in building this library. We would like to use your node in our project. 

Can you let us know what BSD license have been assigned to this library?

Thanks
Kandy

**Comment by Kandy16** [comment]
Hey Everyone,

We have built a commercial application using your node and have hold our release because of the lack of license information of this particular module. There is a bit of urgency and pressure on us to make the release.

I request you to reveal the license information as soon as possible which will be very helpful for us.

Thanks In Advance
Kandy

**Comment by jaredsmith** [comment]
I'd also like some clarification on the license, please.  And if you could, please include a LICENSE file in the source with a copy of the license text.

**Comment by Artoria2e5** [comment]
The license id in package.json is simply invalid. `BSD` is not in the list of SPDX License IDs: https://spdx.org/licenses/.

**Comment by wayfind** [comment]
Thanks for suggestion. I have add a LICENSE file into project.

**Comment by jaredsmith** [comment]
Thank you!
