### ISSUE TITLE
微博观光团到此一游

### ISSUE THREAD

**Issue by blackmiaool** [wayfind/is-utf8#5]

**Comment by justjavac** [comment]
一游

**Comment by Artoria2e5** [comment]
LOL. It's time to add something more interesting to utf8.txt.

**Comment by jinghu-okta** [comment]
前排占座

**Comment by jinghu-okta** [comment]
占个座先

**Comment by whwnow** [comment]
@Arthur2e5 +1024

**Comment by DD-L** [comment]
...

**Comment by zhangjh** [comment]
前排留名~

**Comment by MaskWu** [comment]
哥们要炸

**Comment by 4garfield** [comment]
the utf8.txt is out of date...... :)

**Comment by sungerk** [comment]
@justjavac 大神炒作高手也.  
老实说你从来没用过炒作，正因为你反感炒作。 为什么你反感，因为你完全有开发炒作的能力，炒作的底层你都了如指掌。
虽说你反感炒作，但是炒作却占有大量的用户份额，之后你有个想法，不如重新开发一个属于自己思想，自己架构的炒作。
你给了他一个霸气的名字：MingGe炒作，
它的名字叫MingGe炒作，MingGe就是你的大名， 一看到炒作名字，就知道作者是你，知道它是国产的，让别人知道国产炒作一样做得很出色，出众！
你是mingge 请支持国产mingge炒作，因为我们都是中国人。

**Comment by justjavac** [comment]
@sungerk 你进错了，这个不是 minggeJS，这个是 wayfind 的 is-utf8

**Comment by sungerk** [comment]
@justjavac   不，我已经认得出你了。请收下我的膝盖...

**Comment by justjavac** [comment]
@sungerk 我很反感膝盖，因为膝盖的底层了如指掌

**Comment by sungerk** [comment]
@justjavac  我很反感别人反感膝盖，因为反感膝盖的底层了如指掌

**Comment by junhey** [comment]
一下就火了

**Comment by spaceshiplyf** [comment]
twitter观光团路过

**Comment by sabrinaluo** [comment]
微博观光团路过ヽ( ￣д￣;)ノ

**Comment by ghost** [comment]
前端猎头找人时路过留念……搜寻武汉前端ing
